//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewTempEntities : DbContext
    {
        public NewTempEntities()
            : base("name=NewTempEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<samsung> samsungs { get; set; }
        public virtual DbSet<qmobile> qmobiles { get; set; }
        public virtual DbSet<oppo> oppoes { get; set; }
        public virtual DbSet<lg> lgs { get; set; }
        public virtual DbSet<iphone> iphones { get; set; }
        public virtual DbSet<huawei> huaweis { get; set; }
        public virtual DbSet<gridView> gridViews { get; set; }
    }
}
